# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FAODownloader
                                 A QGIS plugin
 Downloads rasters from the FAO severs.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-14
        copyright            : (C) 2023 by Brenden Vissers / Celray James Chawanda

        email                : BVissers929@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FAODownloader class from file FAODownloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .FAO_Downloader import FAODownloader
    return FAODownloader(iface)
