# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WaporDataTool
                                 A QGIS plugin
 This plugin downloads and analyses WaPOR data for a selected region
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-26
        copyright            : (C) 2022 by Brenden & Celray James
        email                : celray@chawanda.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WaporDataTool class from file WaporDataTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .waport_data import WaporDataTool
    return WaporDataTool(iface)
